### PR TITLE
Add php project with 3rd party library.

### PR DESCRIPTION
**Pull request by rabbah**
This is a simple php project with a third party library installed using `php composer`. Ideally the `build.sh` isn't needed and the equivalent of "npm install" for php is done automatically for you.

### CODE REVIEW

**Review by joshuaauerbachwatson — COMMENTED** [review]
I don't know php so I'm going to assume the code works for a php user.  I tried applying the change and got 
```
./build.sh: line 5: composer: command not found

Failures:
 ›   Error: While deploying action 'n2w': './build.sh' exited with code 127
```
I assume that a php user would have `composer` installed (whatever that is).  You mention elsewhere that this example fails remote build.   Does our php runtime container include `composer`?

Not sure how you want me to proceed with a review.  I can find and install `composer` (or you can tell me where to get it).

**Comment by rabbah** [comment]
composer is to php what npm is to node. 
You can install it by following the docs https://getcomposer.org/doc/00-intro.md

This example works locally with composer installed.

I could certainly have build.sh issue a more  meaningful message when composer isn’t detected. In fact I can apply this particular enhancement to our Java example which require mvn/gradle.

**Comment by rabbah** [comment]
Our php runtime does include composer https://github.com/nimbella-corp/openwhisk-runtime-php/blob/2ceb6f3b2d87a2deae7004c98e34c6d96fb2ded4/core/php7.4Action/Dockerfile#L70

I don’t believe the remote build actually gets to the point in the build where it matters.

**Comment by rabbah** [comment]
The reason to delay a merge is the added composer requirement. I wasn’t sure if that complicates any downstream builds we have. If there are none, then this pr should be merged.

**Comment by joshuaauerbachwatson** [comment]
>  I wasn’t sure if that complicates any downstream builds we have. If there are none, then this pr should be merged.

Our production build whitelists demo projects that are actually installed in the Nimbella cloud.  Demos that are not explicitly listed are ignored by that build and will be harmless.  I don't know of other downstream builds that could be affected.

**Review by joshuaauerbachwatson — APPROVED** [review]
I installed composer and verified this working.

**Pull request merged**
